#!/bin/bash
set -e

# Configure install destination
if [ $# -eq 0 ]; then
  DEVCLI_INSTALL_DIR=$HOME/bin/dev-cli # TODO: change ~ into $HOME ?
else
  DEVCLI_INSTALL_DIR="$1"
fi

# Create app folder
mkdir -p ~/.dev-cli

mkdir -p $DEVCLI_INSTALL_DIR
cp -r ./src/* $DEVCLI_INSTALL_DIR

sed -i '/# Artemoire\/dev-cli/,/^$/d' ~/.bashrc
echo "# Artemoire/dev-cli
export PATH=\"$DEVCLI_INSTALL_DIR:\$PATH\"
" >> ~/.bashrc

echo "Installed dev-cli into $DEVCLI_INSTALL_DIR"