#!/bin/bash

arg="$1"
shift
case "$arg" in
  configure)
  . $DEVCLI_WORKDIR/lib/commands/profile-configure $@
  ;;
  set)
  . $DEVCLI_WORKDIR/lib/commands/profile-set $@
  ;;
  sync)
  . $DEVCLI_WORKDIR/lib/commands/profile-sync
  ;;
  help)
  . $DEVCLI_WORKDIR/lib/help/commands/profile
  ;;
  *)
  . $DEVCLI_WORKDIR/lib/help/commands/profile
  exit 1
  ;;
esac