#!/bin/bash

__assert_argdef "<profile-name>" "Usage: dev profile default <profile-name>" $1

! __check_file_exists $DEVCLI_PROFILE_DIR/$1 && echo "Invalid <profile-name>: Profile \"$1\" doesn't exist." && exit 1

echo "$1" > $DEVCLI_PROFILE_DIR/$DEVCLI_PROFILE_DEFAULT
echo "Set default profile to ($1)."
