#!/bin/bash

DEVCLI_PROFILE_DEFAULT=.default
DEVCLI_PROFILE_DIR=~/.dev-cli

__load_profile() {
  if test -e $DEVCLI_PROFILE_DIR/$DEVCLI_PROFILE_DEFAULT; then
    DEVCLI_PROFILE=$(cat $DEVCLI_PROFILE_DIR/$DEVCLI_PROFILE_DEFAULT)
  fi

  if [ ! -n "$DEVCLI_PROFILE" ]; then
    DEVCLI_PROFILE="(none)"
  fi
}