#!/bin/bash

DEVCLI_PROFILE_DEFAULT=.default

__load_profile() {
  if test -e $DEVCLI_USER_DIR/$DEVCLI_PROFILE_DEFAULT; then
    DEVCLI_PROFILE=$(cat $DEVCLI_USER_DIR/$DEVCLI_PROFILE_DEFAULT)
  fi

  if [ ! -n "$DEVCLI_PROFILE" ]; then
    DEVCLI_PROFILE="(none)"
  fi
}