#!/bin/bash
DEVCLI_WORKDIR=$(cd $(dirname $0) && pwd)
. $DEVCLI_WORKDIR/lib/functions/assertions
. $DEVCLI_WORKDIR/lib/functions/ssh
. $DEVCLI_WORKDIR/lib/functions/checks
. $DEVCLI_WORKDIR/lib/functions/profile

__load_profile

arg="$1"
shift
case "$arg" in
  profile)
  . $DEVCLI_WORKDIR/lib/commands/profile $@ 
  ;;
  pwd)
  . $DEVCLI_WORKDIR/lib/commands/pwd $@
  ;;
  *)
  . $DEVCLI_WORKDIR/lib/help/dev
  exit 1
  ;;
esac