#!/bin/bash
echo "
Program: dev-cli
Author: Dejan Tot
Version: 0.0.1
Profile: $DEVCLI_PROFILE

Usage: dev [command]

Commands:
  profile    Configure dev profile
  pwd        Prints workspace path with optional [project-dir] argument.
  work       Manage profile work logs
"